/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_tno_stormcv_util_StreamerHelper */

#ifndef _Included_nl_tno_stormcv_util_StreamerHelper
#define _Included_nl_tno_stormcv_util_StreamerHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_tno_stormcv_util_StreamerHelper
 * Method:    sendFirstFrame
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_tno_stormcv_util_StreamerHelper_sendFirstFrame
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     nl_tno_stormcv_util_StreamerHelper
 * Method:    sendNormalFrame
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_tno_stormcv_util_StreamerHelper_sendNormalFrame
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     nl_tno_stormcv_util_StreamerHelper
 * Method:    connectToRtmp
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_nl_tno_stormcv_util_StreamerHelper_connectToRtmp
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
